### ISSUE TITLE
You may want to stop using arrow functions as class properties

### ISSUE THREAD

**Issue by m-przybylski** [meetjspl/krakow#10]
# Title: You may want to stop using arrow functions as class properties
### Type: 

  - [x] Presentation (from 25 min to 40 min)
  - [ ] Lightning talk (from 5 min to 15 min)

### Language:
  
  - [x] Polish
  - [x] English

### Description:
```
I would like to share my story about how and why we went from using arrow function as class
properties to regular functions. The journey will cover discovering the problem, how we decided to
address all the issues, what tools we used to solve all the problems.
```

  - [x] I've read the [README Promotion section](https://github.com/meetjspl/krakow)
  - [x] I allow for my name/image/email to be used to promote the meetup
  - [x] I promise to share my presentatio later publictly here and in a comment on meetup.com

# Author information

### Bio ( max 200 words):
```
I am Front-End software engineer with over 10 years of professional experience. I love spending time
with other 🧑🧑 exchanging ideas and talking about new technologies over a 🍺. I'm also a big fun
of 🏍️ 
 ```

### Social media

  - FB: https://www.facebook.com/maciej.przybylski.161
  - GitHub: https://github.com/m-przybylski/
  
# When I'm available:
* I will be ready to give the talk end of April.

**Comment by sptq** [comment]
The next Meet.js Kraków will be on 27 June - could you present this topic on meetup or next month?

**Comment by m-przybylski** [comment]
Sure, I will be ready by that time.
