### ISSUE TITLE
Modern Monorepo with Lerna

### ISSUE THREAD

**Issue by michaljach** [meetjspl/krakow#19]
# Modern Monorepo with Lerna
### Type: 

  - Presentation (from 25 min to 40 min)

### Language:
  
  - Polish
  - English

### Description:
```
Have you ever struggled with maintaining multiple, dependant repositories?
Are you tired of npm linking nad building dependencies all over again?
Organize your codebase with monorepo approach and never struggle again!
With Lerna you can save tremendous amount of time and nerves. HMR works!
Make your codebase way easier to maintain and speed your
development process using Monorepo approach just like Facebook, Twitter or Google.
```

  - [ x ] I've read the [README Promotion section](https://github.com/meetjspl/krakow)
  - [ x ] I allow for my name/image/email to be used to promote the meetup
  - [ x ] I promise to share my presentatio later publictly here and in a comment on meetup.com

# Author information

### Bio ( max 200 words):
```
Senior Javascript Developer, iOS Wannabe Developer,
Xiaomi scooter hacker, overall computer operator.
```

### Social media

  - GitHub: https://github.com/michaljach
  
# When I'm available:

October 24th

**Comment by krzychukula** [comment]
@michaljach You will be first on 24.10 and your talk will be in English. Please let us know as soon as possible what the length of your presentation will be so that we could put exact hours into the agenda :)

**Comment by krzychukula** [comment]
@michaljach Please take a look at the draft and let me know if everything is ok: https://www.meetup.com/KrakowJS/events/265212457/
I've made small changes as suggested by `Grammarly` I'm using. Feel free to let me know if I should undo them? Anything that you want to change or that needs fixing?

**Comment by michaljach** [comment]
Hey!
Yes its perfect :) my talk will be around 20 minutes. 
Thanks 

MJ
