### ISSUE TITLE
Twórz lepsze strony jeszcze szybciej dzięki Gatsby.js 

### ISSUE THREAD

**Issue by helloroman** [meetjspl/krakow#2]
# Title: Twórz lepsze strony jeszcze szybciej dzięki Gatsby.js 
### Type: 

  - [x] Presentation (from 25 min to 40 min)
  - [ ] Lightning talk (from 5 min to 15 min)

### Language:
  
  - [x] Polish
  - [ ] English

### Description:
```
Jeśli zajmujesz się frontendem wystarczająco długo, to pewnie pamiętasz czasy, gdy używaliśmy do tworzenia stron wyłącznie HTML, CSS i JavaScriptu (ze szczyptą jQuery). Pamiętasz też pewnie wszystkie te ciężkie chwile zmagań z typografią, optymalizacją obrazków, przygotowywaniem odpowiednich rozmiarów plików... wyobraź sobie wszystkie te stracone godziny. 

Na szczęście od tamtych czasów już sporo minęło i sporo się zmieniło, a technologie frontendowe dość mocno poszły do przodu. Z każdym rokiem przybywa narzędzi, które ułatwiają nam życie i pozwalają część tych nieprzyjemnych zadań powierzać komputerowi. Jednym z tych narzędzi jest Gatsby.js – nowoczesny generator stron statycznych oparty o znanego i lubianego Reacta. W mojej prezentacji pokażę kilka kluczowych funkcji kryjących się za Gatsbym, oraz udowodnię, że to jedno z najfajniejszych rozwiązań do tworzenia statycznych stron.
```

  - [x] I've read the [README Promotion section](https://github.com/meetjspl/krakow)
  - [x] I allow for my name/image/email to be used to promote the meetup
  - [x] I promise to share my presentatio later publictly here and in a comment on meetup.com

# Author information

### Bio ( max 200 words):
```
Cześć! Nazywam się Adam Romański i sam siebie nazywam kreatywnym front-endowcem, ponieważ zanim dołączyłem do branży IT, wiele lat spędziłem pracując jako copywriter w agencjach reklamowych. 

Na co dzień pracuję w jednym z największych software house'ów w Polsce, realizując ambitne projekty dla zagranicznych klientów. Dzięki tej pracy zdobyłem sporo doświadczenia, którym uwielbiam się dzielić.

W moim przypadku pasja do uczenia innych przejawia się także w inny sposób. „Po godzinach” zajmuję się vlogiem Hello Roman na YouTube, który w kilka miesięcy zdobył prawdziwą rzeszę fanów. 
Za pośrednictwem vloga opowiadam o moich przemyśleniach dotyczących programowania, branży IT, a także tworzę materiały z praktycznymi, technicznymi poradami.

Do tej pory zrealizowałem wiele projektów zarówno w React, Vue, Gatsby jak i innych technologiach, dzięki czemu poczułem się dość komfortowo w fascynującym ekosystemie JavaScriptu. 

```

### Social media

  - FB: https://www.facebook.com/helloroman.vlog
  - GitHub: https://github.com/helloroman
  - YouTube: https://youtube.com/helloroman

**Comment by sptq** [comment]
Cześć Adam!

Dziękujemy za złożenie zgłoszenia. Pytanie: Czy możesz wystąpić w Lutym, czy na Marcowym Meet.js?

**Comment by helloroman** [comment]
Hej Marcin, 

rozmawiam już z Krzysztofem Kulą na temat meetingu – ten issue pojawił się na jego prośbę. Celowałem w meeting lutowy, ale jeśli się nie załapię to marzec też spoko – tylko pytanie kiedy to będzie :) Bo mam w marcu jeszcze jeden wyjazd. 

pozdrawiam serdecznie,
Adam 

PS kontaktujmy się przez mojego vlogowego maila – bo ten githubowy jest przypięty do firmy.
