### ISSUE TITLE
Towards more algebraic TypeScript

### ISSUE THREAD

**Issue by belfz** [meetjspl/krakow#3]
# Towards more algebraic TypeScript
### Type: 

  - [x] Presentation (from 25 min to 40 min)
  - [ ] Lightning talk (from 5 min to 15 min)

### Language:
  
  - [ ] Polish
  - [x] English

### Description:
```
Is it possible to bring the type-safety to a whole new level? How about never using 'undefined' again? In this talk I will share my experience with few algebraic structures that made my projects' domain & presentation layer safe again.
```

  - [x] I've read the [README Promotion section](https://github.com/meetjspl/krakow)
  - [x] I allow for my name/image/email to be used to promote the meetup
  - [x] I promise to share my presentation later publicly here and in a comment on meetup.com

# Author information

### Bio ( max 200 words):
```
Senior frontend developer @ SoftwareMill. Used to be involved in the development of wasm-bindgen, a Rust/WebAssembly to JS bridge. Interested in the theory & practice of functional programming, recently trying out his skills in Scala.
```

### Social media

  - FB: https://www.facebook.com/koyaanisqatsii
  - Twitter: https://twitter.com/marcin_ba
  - GitHub: https://github.com/belfz
  
# When I'm available:
Starting from the second half of ~March~ April ~(no earlier than 18th of March).~

**Comment by belfz** [comment]
Due to the unforeseen circumstances in the commercial project I work with, I had to postpone my availability to late April (updated in the description above).

**Comment by sptq** [comment]
The next Meet.js Kraków will be on 27 June - could you present this topic on meetup or next month?

**Comment by wojtczal** [comment]
@belfz do we need any update to this description? :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
