### ISSUE TITLE
React forms done right

### ISSUE THREAD

**Issue by lkostrowski** [meetjspl/krakow#4]
# Title: React forms done right
### Type: 

  - [x] Presentation (from 25 min to 40 min)
  - [ ] Lightning talk (from 5 min to 15 min)

### Language:
  
  - [x] Polish (preferred)
  - [x] English

### Description:
```
Talk about clean, functional and testable forms using Formik (maybe some alternatives, we will see).
- benefits of abstracting form state and UI
- how to handle dynamic inputs number
- standardised validations
- connecting to redux state
```

  - [x] I've read the [README Promotion section](https://github.com/meetjspl/krakow)
  - [x] I allow for my name/image/email to be used to promote the meetup
  - [x] I promise to share my presentatio later publictly here and in a comment on meetup.com

# Author information

### Bio ( max 200 words):
```
Frontend developer, React and Typescript enthusiast (TBD)
```

### Social media

  - FB:
  - Twitter:
  - GitHub: 
  
# When I'm available:

* From March

**Comment by sptq** [comment]
The next Meet.js Kraków will be on 30 May - could you present this topic on meetup?

**Comment by lkostrowski** [comment]
No, can't prepare in 3 days.

Closing it for now, I have busy next 3 months
