### ISSUE TITLE
Immutability in JS

### ISSUE THREAD

**Issue by hypeofpipe** [meetjspl/krakow#6]
# Title: Immutability in JS
### Type: 

  - [X] Presentation (from 25 min to 40 min)
  - [ ] Lightning talk (from 5 min to 15 min)

### Language:
  
  - [ ] Polish
  - [X] English

### Description:
```
The immutability concept is being more popular over the last years, even Rust has implemented that feature for variables by default. There are some tricks to bring more mutability-proof code in modern JS.

```

  - [X] I've read the [README Promotion section](https://github.com/meetjspl/krakow)
  - [X] I allow for my name/image/email to be used to promote the meetup
  - [X] I promise to share my presentation later publicly here and in a comment on meetup.com

# Author information

### Bio ( max 200 words):
```
Hi! I'm a full-stack web developer. Programming is my passion. I started programming because my passion for gamedev, but now I do more Web, finds out, that it is amazing as well :) I try to do my best as a programmer in learning new stuff, there is a lot of things I don't know yet - amazing. 
```

### Social media

  - FB: 
  - Twitter:
  - GitHub: https://github.com/hypeofpipe
  
# When I'm available:

From mid-March

**Comment by sptq** [comment]
The next Meet.js Kraków will be on 30 May - could you present this topic on meetup?

**Comment by hypeofpipe** [comment]
Hello, unfortunately – no. My finals are on fire, and as full time student I can't afford it :( 
And the other thing is that I already gave the presentation on the same topic recently :(

**Comment by sptq** [comment]
What about 27 of June?

**Comment by wojtczal** [comment]
@hypeofpipe Are you still interested in presenting on this topic or should we close this issue?

**Comment by hypeofpipe** [comment]
Hello, we can close the issue, thank you 🙌
