### ISSUE TITLE
A Gentle Introduction To WebAssembly

### ISSUE THREAD

**Issue by MarekLabuz** [meetjspl/krakow#8]
# Title: A Gentle Introduction To WebAssembly
### Type: 

  - [x] Presentation (from 25 min to 40 min)
  - [ ] Lightning talk (from 5 min to 15 min)

### Language:
  
  - [ ] Polish
  - [x] English

### Description:
```
When I saw WebAssembly in action for the first time, I was really impressed. 
So, I've deepened my knowledge since then and finally I feel comfortable enough to share it with you. 
This talk aims to provide information about:
- What is WebAssembly?
- Why do we need WebAssembly?
- How can we use WebAssembly today?
- What are the current limitations of WebAssembly and what is going to change in the future?

```

  - [x] I've read the [README Promotion section](https://github.com/meetjspl/krakow)
  - [x] I allow for my name/image/email to be used to promote the meetup
  - [x] I promise to share my presentatio later publictly here and in a comment on meetup.com

# Author information

### Bio ( max 200 words):
```
I'm a Full Stack Software Developer, mostly interested in JavaScript (Typescript, React, Node.js), C/C++ and Golang

```

### Social media

  - FB:
  - Twitter:
  - GitHub: 
  
# When I'm available:

* Anytime

**Comment by sptq** [comment]
The next Meet.js Kraków will be on 27 June - could you present this topic on meetup or next month?

**Comment by MarekLabuz** [comment]
Thank you for the information. I'll be ready with the presentation for the 27th of June
